### PR TITLE
Make ProhibitBarewordFileHandles catch sysopen and opendir as well

### PR DESCRIPTION
**Pull request by tadzik**

### CODE REVIEW

**Comment by petdance** [comment]
Thanks for the PR.

Someone will need to add tests before we can commit this.  Also, we should use a list of strings to `eq` against rather than a regex.

**Comment by tadzik** [comment]
I considered a list of strings, but eventually went for a regex since it's easier (for me to write anyway) a match rather than a grep over a list or something from List::(More)Util(s). And yes, I was looking for tests too, but it seems like this policy doesn't have any at all; I tested it manually, but I'd feel better too if it had a testcase to go along with it :­)

**Comment by petdance** [comment]
If we can get some tests on this, I'd be glad to include it.

**Comment by petdance** [comment]
Done.  6d04f0cf

**Pull request closed without merging**
