### PR TITLE
add allow_our option to ProhibitAugmentedAssignmentInDeclaration

### PR DESCRIPTION
**Pull request by haarg**
Since our variables can have values prior to their declaration, it is much more reasonable to have an augmented assignment when declaring an our variable.

Add an option `allow_our` which will allow this.

### CODE REVIEW

**Comment by petdance** [comment]
This seems like a reasonable thing to add. Looks like it fails on 5.8, though.

**Comment by haarg** [comment]
That is due to the prereqs failing to install, because podlators now requires perl 5.10.

**Comment by petdance** [comment]
Thanks for the diagnosis. Hmm. Maybe we just punt on 5.8 from 2002 at this point.

**Comment by petdance** [comment]
I'll do this when I'm done with #994.

**Comment by petdance** [comment]
Done, thank you.

**Pull request merged**
