### PR TITLE
Fix scope calculation

### PR DESCRIPTION
**Pull request by trwyant**
This pull request addresses some problems with the Perl::Critic::Document method element_is_in_lexical_scope_after_statement_containing(). Specifically:

* There is a fencepost error in trying to determine if the two elements are in the same statement;

* The list of the for() and foreach() builtins is not in-scope to the iteration variable;

* The right-hand side of a 'my' with assignment is not in-scope to its left-hand side.

This is a public method, but in all of CPAN as of a couple days ago there were only two uses: in Perl::Critic::Document itself to figure out what the default regexp qualifiers are, and in standalone policy Variables::ProhibitUnusedVarsStricter. Perl::ToPerl6::Document has a same-named method that appears to be a cut-and-paste of an earlier version of the method being patched.

Because this method has no tests specific to it, I regression-tested the changes by running Variables::ProhibitUnusedVarsStricter against CPAN, using both old and new versions of this method. The output contained about 500 difference sections, a few of which comprised multiple lines of test failures. I have only reviewed the first 102 differences, and the scorecard is:

False negative in old code.                -    4
False positive in new code. PPI mis-parse. -    5
False positive in new code. Policy error.  -    1
False positive in old code.                -   92

The false positives in the new code are generally the result of PPI thinking that all uses of the symbol are in a part of the code no longer in scope. About half of these represent code that does not compile, and the others are pathological (to me, at least) in other ways leading to a PPI mis-parse. The policy error is the value returned by an lvalue subroutine which does not use a 'return' statement. I'm not sure what to do about it, but if someone complains to you about it, please pass it to me, because it will have to be fixed in ProhibitUnusedVarsStricter if anywhere.

The following is context on how the code got the way it is.

Method element_is_in_lexical_scope_after_statement_containing() was written by me when I was active as part of the Perl::Critic team and trying to come up with a version of core policy Variables::ProhibitUnusedVariables that was more stringent. The long-named method was hung on Perl::Critic::Document because I anticipated it being useful for other things (true), and because I thought some caching might be needed for better performance (false, so far).

### CODE REVIEW

**Comment by petdance** [comment]
Thanks for this.  I will try to look at it tomorrow.

**Comment by trwyant** [comment]
Off-the-wall thought:

This code is really more PPI-ish than it is Perl-Critic-ish. If you like, I could pull it out into its own module, and you would not have to administer it. Of course, since the code is used to determine which 'use re' statements are in-scope to a regular expression, Perl-Critic would have to depend on the new module, and if I screwed up it would still break Perl-Critic. So you might prefer to keep this code under your eye.

Your call.

**Comment by petdance** [comment]
Do you see anyone using it outside of P::C?

**Comment by trwyant** [comment]
Not other than me. There is a distro that "uses" it, but it is a cut-and-paste copy, not the actual code.

Sorry for the long delay in replying.

**Comment by trwyant** [comment]
Well, the previous comment was careless. A more precise answer is that the only uses of this code I have found in CPAN are Perl::Critic itself and Perl::Critic::Policy::Variables::ProhibitUnusedVariables. Perl::ToPerl6 uses a copy of an early version of this code.

There. That's clearer, I hope.

**Comment by petdance** [comment]
Thanks. Does this Changes file comment cover it? 1e03a618

**Pull request merged**
