### PR TITLE
add support for experimental:: categories in ProhibitNoWarnings policy

### PR DESCRIPTION
**Pull request by reneeb**

### CODE REVIEW

**Comment by petdance** [comment]
Thanks for this.  Can you please write up a description of the change that we can put in the changelog to let folks know why this is useful?

**Comment by reneeb** [comment]
Back in Perl 5.18 a new warnings category was introduced: "experimental". Every experimental feature (e.g. signatures, postderef, etc.) get its own warnings ID (e.g. experimental::signatures). So to use the signatures feature and disable the warnings, you see

```
use feature 'signatures';
no warnings 'experimental::signatures';
```

The critic policy ProhibitNoWarnings allows to define a list of exceptions (e.g. `allow=utf8`) that worked only with categories (e.g. utf8, redefine,...) that have only alphanumeric values in its name. Now the policy supports the `experimental::...` warnings, too.

**Comment by petdance** [comment]
That will work.  Do you think it's something that should be mentioned in the docs for the policy, or not?

**Comment by reneeb** [comment]
I don't think that this needed.

**Comment by petdance** [comment]
Merged. Thank you.

**Comment by petdance** [comment]
This has been released as v1.135_01.

**Comment by petdance** [comment]
And I've now uploaded 1.136.  Thanks.

**Pull request merged**
