### PR TITLE
Fix #843 false positive in ProhibitPunctuationVars

### LINKED ISSUE #843: Wrong detection of qr/SOME$/ in regexp
regular expression like `qr/SOME$/xsm` perlctitic detect magic punctuation: `$/`

```
lsopov@mac ~ $ perlcritic /tmp/1.pl
Magic punctuation variable $/ used in interpolated string at line 9, column 1.  See page 79 of PBP.  (Severity: 2)
Magic punctuation variable $/ used in interpolated string at line 11, column 1.  See page 79 of PBP.  (Severity: 2)
lsopov@mac ~ $ cat -n /tmp/1.pl
     1	#!/usr/bin/perl
     2
     3	use strict;
     4	use warnings;
     5
     6	our $VERSION = 1;
     7
     8	/test$/xsm;
     9	qr/test$/xsm;
    10	/TEST$/xsm;
    11	qr/TEST$/xsm;
lsopov@mac ~ $
```

### PR DESCRIPTION
**Pull request by trwyant**
Fix #843: Delegated interpretation of regexen to PPIx::Regexp, which is already a prerequisite.

There are failures in t/05_utils.t and xt/40_criticize-code.t, but they were present before I started working on this.

### CODE REVIEW

**Comment by petdance** [comment]
Thanks for the changes.  I'm not comfortable using internal methods to PPIx::Regexp::Util, since as the docs say "The contents of this module are private to the PPIx::Regexp package. This documentation is provided for the author's convenience only. Anything in this module is subject to change without notice. Caveat user."

I'd be fine with it if PPIx::Regexp::Util were updated to upgrade `__is_ppi_regexp_element` to an underscore-less function.

**Comment by trwyant** [comment]
Quite right. I'm the author of PPIx::Regexp, which has made me careless about this sort of thing.

I will update PPIx::Regexp::Util as seems appropriate, and let you know when I have done so. OK?

**Comment by petdance** [comment]
Sounds good, thanks.

I'm assuming you'll have it done fairly quickly, so I'll hold off on a Perl::Critic release that includes your other PR I just merged this morning.

**Comment by trwyant** [comment]
Just pushed to https://github.com/trwyant/perl-PPIx-Regexp

If this looks OK, I will do a development release, give CPAN Testers a few days to chew on it, and then a production release.

**Comment by trwyant** [comment]
PPIx::Regexp 0.067_01 just went to PAUSE. My usual system is to let the CPAN testers have a week, and then do a production release. After that, I will see if my git (and GitHub)-fu are up to updating the pull request.

**Comment by trwyant** [comment]
Just sent PPIx-Regexp 0.068 to PAUSE, updated the pull request code, and pushed to GitHub.

There were no changes in PPIx-Regexp from 0.067_01 other than the version. There was a single "unknown" testing result, but that was "no makefile found" so I assume it's a smoker problem. Here's the test: http://www.cpantesters.org/cpan/report/140f0fc0-3b2c-11ea-bf89-9f47312aa01a

The Perl-Critic update also updates the version of PPIx::Regexp::Util required. There were the same two test failures as when I started. There is a Travis CI failure which I interpret as being because PPIx-Regexp 0.068 has not propagated that far yet. Sorry about that.

Please let me know what else you need from me.

**Comment by petdance** [comment]
> Please let me know what else you need from me.

Are there other test cases we should be stress-testing?

**Comment by trwyant** [comment]
Don't know about test cases.

I see the Travis and Appveyor checks still show failure, but the latest is 2 days ago and the complaint appears to boil down to wrong version of PPIx::Regexp::Util. The current version is 0.068. This was published a couple days ago, and it was indexed, at least as I read https://www.cpan.org/modules/02packages.details.txt.gz

Do I need to do something here?

**Comment by petdance** [comment]
> Do I need to do something here?

I don't think so.  I just haven't had time to do the release yet.

**Comment by trwyant** [comment]
No sweat. I just saw the failures and knew I was the last one to touch the code.

**Comment by petdance** [comment]
Merged and about to be released in 1.137_01.  Thank you as always.

**Pull request closed without merging**
