### PR TITLE
Add terminals parameter to ProhibitUnreachableCode.

### PR DESCRIPTION
**Pull request by bluefeet**
Found that I wanted `done_testing` added.  Rather than just hardcode it I made it a parameter.

### CODE REVIEW

**Comment by bluefeet** [comment]
Well, neither does `last` or `next` or `goto`.  Terminating statements in the context of this module are not those that just terminate the program, they just terminate execution beyond their current location.

**Comment by petdance** [comment]
I was under the impression that `done_testing()` is just a notice to the harness to stop counting tests.  Are you saying it affects program flow, too?

**Comment by petdance** [comment]
And maybe `terminals` isn't the term to use, then?

**Comment by petdance** [comment]
The behavior of done_testing doesn't relate to whether this is a good patch or not.  I just don't think we want to use it as an example.

```
$ cat foo.pl
#!/usr/bin/perl

use warnings;
use strict;
use 5.010;

use Test::More tests => 3;

pass( 'One' );
pass( 'Two' );

done_testing();

pass( 'Three' );
diag( "I am still here" );
```

```
$ perl foo.pl
1..3
ok 1 - One
ok 2 - Two
not ok 3 - planned to run 3 but done_testing() expects 2
#   Failed test 'planned to run 3 but done_testing() expects 2'
#   at foo.pl line 12.
ok 4 - Three
# I am still here
# Looks like you planned 3 tests but ran 4.
# Looks like you failed 1 test of 4 run.
```

**Comment by bluefeet** [comment]
OMG you called me out on an assumption I was making about `done_testing`.  I feel very embarrassed.  You are completely right, and it is a bad example for this module (but still could be a valid use case).  :)

And yes, terminals is probably not the greatest word.  I was going to just call it `functions` originally.

**Pull request closed without merging**
