### PR TITLE
Tidy some test imports

### PR DESCRIPTION
**Pull request by oalders**
I'm just testing out https://metacpan.org/pod/perlimports and I figured I'd run it against the `Perl::Critic` test suite.

I'd be interested in knowing if you find these changes useful, objectionable, a waste of time or some combination of the above. 

I've documented the motivation for these changes at https://metacpan.org/pod/App::perlimports and I'm happy to receive any and all feedback on this very much unsolicited pull request. 😄

### CODE REVIEW

**Comment by petdance** [comment]
I think that cleaning up imports is a good thing.  No point in importing a symbol that isn't used.

I'm undecided on whether adding an empty `()` on a `use Foo` that doesn't import anything is good or bad.

I don't want to change `qw<>` to `qw()` for the sake of using parens instead of angle brackets.

**Comment by oalders** [comment]
Thanks. This is very helpful feedback.

> I think that cleaning up imports is a good thing. No point in importing a symbol that isn't used.

😃 

> I'm undecided on whether adding an empty () on a use Foo that doesn't import anything is good or bad.

That's an interesting point. At $work we've standardized on empty parens even for OO modules because when you're looking at 10-30 import statements, it immediately becomes clear that those modules are not implicitly importing anything. Another plus there is that when you do have something like `use Moose;`, that becomes an indicator that you should be aware that implicit imports are taking place.'

> I don't want to change qw<> to qw() for the sake of using parens instead of angle brackets.

Good point as well. In this case it wasn't clear that there was a consistent preference for either style of brackets. This does make it consistent across more cases, but I can see that the churn might seem pointless.

**Comment by petdance** [comment]
It's mostly `qw<>` but there are `qw()` as well.

```
$ ack 'qw<' | wc -l
333
$ ack 'qw\(' | wc -l
516
```

The reason I waffle on the `use Foo ();` is that if Foo doesn't export anything, it doesn't do anything useful, other than documentation.  On the other hand, documentation is a big part of why we would do the explicit `()` in the first place.

**Comment by oalders** [comment]
Thanks for the feedback! I'm going to close this now.

**Pull request closed without merging**
