### PR TITLE
Try to address is_hash_key false positive on function call inside hash index

### PR DESCRIPTION
**Pull request by eldering**
This is my attempt at a fix for #1071. It works for my case, but I'm not sure it covers all edge cases correctly.

### CODE REVIEW

**Comment by petdance** [comment]
Thanks for this. At the very least we'll also need a positive and negative test case for the problem you're addressing.

**Comment by eldering** [comment]
> Thanks for this. At the very least we'll also need a positive and negative test case for the problem you're addressing.

Added, also a test for a hash key in front of a fat comma in a hash construction list that seemed to be missing.

**Comment by eldering** [comment]
@petdance would you be able to have a look at this?

**Comment by petdance** [comment]
Looks OK to me. I'll try to put something out tomorrow. Don't have time tonight.

**Comment by petdance** [comment]
I've combined your changes and some cleanup on https://github.com/Perl-Critic/Perl-Critic/tree/eldering-dev

**Comment by eldering** [comment]
> I've combined your changes and some cleanup on https://github.com/Perl-Critic/Perl-Critic/tree/eldering-dev

Thanks, LGTM. Will you merge this, or is there anything left for me to do?

**Comment by petdance** [comment]
No now it's up to me.

**Pull request closed without merging**
