### PR TITLE
Support indented heredocs

### LINKED ISSUE #845: ProhibitCaptureWithoutTest does not understand indented heredocs
```
$perlcritic -version
1.132
```

Code:
```
    my $api_response = $dbh->selectrow_arrayref(<<~'_SQL', {}, $bind_param )->[0];
            SELECT COUNT(*)
            FROM foo
            WHERE bar = $1
            _SQL
```
Expected: `perlcritic -3` realizes that that `$1` is included in an uninterpolated intended heredoc, and produces no error.
Actual: `perlcritic -3` produces a `RegularExpressions::ProhibitCaptureWithoutTest` warning.

If we unindent the heredoc, as in:
```
    my $api_response = $dbh->selectrow_arrayref(<<'_SQL', {}, $bind_param )->[0];
SELECT COUNT(*)
FROM foo
WHERE bar = $1
_SQL
```
then `perlcritic -3` does not report a warning.

### PR DESCRIPTION
**Pull request by oschwald**
Now that PPI supports indented heredocs, there were a couple of small changes to make various rules work with them. Closes #845 (in as much as that was about indented heredocs working).

### CODE REVIEW

**Comment by oschwald** [comment]
The AppVeyor failure also seems to happen for me on `dev`. I don't think it is related to my changes.

**Comment by oalders** [comment]
@petdance is there anything else we can do to get this merged and released?  It would help us with some pain points at $work.

**Comment by petdance** [comment]
Does anyone have any clue what the build failures are?

**Comment by petdance** [comment]
Also, we need to have test cases added to the test suite to validate the new behavior.

**Comment by oalders** [comment]
```sh
not ok 139 - parse_arg_list: foo( { bar() }, {}, 'blah' )

#   Failed test 'parse_arg_list: foo( { bar() }, {}, 'blah' )'
#   at t/05_utils.t line 433.
#     Structures begin differing at:
#          $got->[0] = ARRAY(0x7fadd0c27030)
#     $expected->[0] = ' { bar() }'
ok 140 - count PPI::Token::Words
...
# Looks like you failed 1 test of 156.
Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/156 subtests

Test Summary Report
-------------------
t/05_utils.t (Wstat: 256 Tests: 156 Failed: 1)
  Failed test:  139
  Non-zero exit status: 1
```

This appears to begin with PPI-1.248, possibly due to https://metacpan.org/diff/file?source=MITHALDU/PPI-1.246&target=MITHALDU/PPI-1.248#lib/PPI/Lexer.pm

**Comment by oalders** [comment]
If I dump `@got` with `Data::Printer`:

```perl
[
    [0] [
        [0] PPI::Structure::Constructor  {
            Parents       PPI::Structure
            public methods (0)
            private methods (0)
            internals: {
                children => [
                    [0] PPI::Token::Whitespace,
                    [1] PPI::Statement,
                    [2] PPI::Token::Whitespace,
                ],
                finish   => PPI::Token::Structure,
                start    => PPI::Token::Structure,
            }
        },
    ],
    [1] [
        [0] PPI::Structure::Constructor  {
            Parents       PPI::Structure
            public methods (0)
            private methods (0)
            internals: {
                children => [],
                finish   => PPI::Token::Structure,
                start    => PPI::Token::Structure,
            }
        },
    ],
    [2] [
        [0] PPI::Token::Quote::Single  {
            Parents       PPI::Token::_QuoteEngine::Simple, PPI::Token::Quote
            Linear @ISA   PPI::Token::Quote::Single, PPI::Token::_QuoteEngine::Simple, PPI::Token::_QuoteEngine, PPI::Token::Quote, PPI::Token, PPI::Element
            public methods (2) : literal, string
            private methods (0)
            internals: {
                content   => ''blah'',
                separator => ''',
            }
        },
    ],
]
```

**Comment by oalders** [comment]
It looks like  `xt/40_criticize-code.t` starts failing at 8f176c210f96749870b7b6a552f51669d1fc9e7f.  However, it may be related to changes introduced in `PPI-1.254`.   I need to check some more permutations, but there's something funky going on there.

**Comment by oalders** [comment]
Once this is sorted it might be nice if `PPI` added an installation of the latest `Perl::Critic` to its Travis tests in order to see if/when changes break things downstream.  @wchristian?

**Comment by oalders** [comment]
I'm looking at the `dev` branch.  2e0fb9de7ac8f9d384 is the commit previous to 8f176c210f96749870b7b6a552f51669d.

When checked out at 2e0fb9de7ac8f9d384 `xt/40_criticize-code.t` passes on `PPI-1.252` and fails on `PPI-1.254`.  When I check out to the next commit (8f176c210f96749870b7b6a552f51669d) then that test just fails even as far back as `PPI-1.220`.

So, I *think* there may be two things going on.  There is something that happened between `PPI-1.252` and `PPI-1.254` and there may be something else entirely that was introduced with 8f176c210f96749870b7b6a552f51669d

**Comment by oalders** [comment]
Merging #863 and bumping the minimum version of `PPI` to `PPI-1.248` would fix `t/05_utils.t`.

**Comment by oalders** [comment]
I'll try to fix `xt/40_criticize-code.t` shortly.  That plus the fixes above should get us back to green lights on the builds.

**Comment by petdance** [comment]
And we still need tests to test the new functionality before we can merge.  Perhaps @oschwald will want to do that since he wrote the code.

**Comment by petdance** [comment]
#863 has been merged.

**Comment by oschwald** [comment]
I went ahead and added test cases. A number of the unit tests still fail locally, but they also fail on the `dev` branch. It does not appear related to this PR.

**Comment by oschwald** [comment]
The Travis failures seem unrelated:

```
===(    6014;35   441/2720  1/?  37/?  0/?  0/?  175/290  0/?  0... )===
#   Failed test 'Test::Perl::Critic for "blib/lib/Perl/Critic.pm"'
#   at /home/travis/perl5/perlbrew/perls/5.28.1/lib/site_perl/5.28.1/Test/Perl/Critic.pm line 121.
# 
#   blib/lib/Perl/Critic.pm: Check the spelling in your POD: O'Regan Hukins Omer Gazit Zacks Howarth Walde Rolsky Jakub Wilk Trosien Creenan Balhatchet Paaske Tørholm Raspass Tonkin Katz Berndt Sergey Gabor Szabo Knop Eldridge Steinbrunner Kimmel Guillaume Aubert Anirvan Chatterjee Rinaldo Ollis Etheridge Brømsø Slaven Rezić Szymon Nieznański at line 1, column 1.  See page 148 of PBP.  (Severity: 1, Documentation::PodSpelling)
xt/80_policysummary.t ......................... ok
===(    6136;35   443/2720  3/?  38/?  0/?  1/?    1/195  0/?  0/? )====
#   Failed test 'Test::Perl::Critic for "blib/lib/Perl/Critic/Command.pm"'
#   at /home/travis/perl5/perlbrew/perls/5.28.1/lib/site_perl/5.28.1/Test/Perl/Critic.pm line 121.
# 
#   blib/lib/Perl/Critic/Command.pm: Use "<>" or "<ARGV>" or a prompting module instead of "<STDIN>" at line 190, column 51.  See pages 216,220,221 of PBP.  (Severity: 4, InputOutput::ProhibitExplicitStdin)
```

**Comment by oalders** [comment]
This should fix the latter failure: https://github.com/Perl-Critic/Perl-Critic/pull/866/commits/6bf9032782dc73d292af9029c7998af257e202d6

**Comment by oalders** [comment]
This should fix the spelling tests: https://github.com/Perl-Critic/Perl-Critic/pull/866/commits/4f1f9a0bf8ab66a4279558275c383e9281304472

**Comment by petdance** [comment]
Merged as 8b384b4.  Thank you!

**Comment by oalders** [comment]
It looks like `dev` is now passing all tests. Are there any more release blockers I should look at?

**Comment by petdance** [comment]
Carried over to #869

**Pull request closed without merging**
