### PR TITLE
Update RequireFinalReturn.pm

### PR DESCRIPTION
**Pull request by xenomorpheus**
Permit specific methods to be considered terminal in subroutines.

Issue discussed at https://github.com/Perl-Critic/Perl-Critic/issues/920

### CODE REVIEW

**Comment by xenomorpheus** [comment]
Hi, Any love for this PR?

**Comment by petdance** [comment]
This has been updated and merged as 1485fcc3c91228640b476bd9990455ed9c439f48. Thank you.

**Comment by xenomorpheus** [comment]
@petdance Thank you for your work in making the changes. Your efforts to help the community are appreciated. Also thank you for acknowledging me in your commit message.  I was really hoping to have my pull request accepted so that I would have been a contributor. Anyway, thank you for your efforts to improve open source software for all.

**Comment by petdance** [comment]
You absolutely are a contributor, and I added you to the Change log.  Thanks very much for the code.

Is there something that GitHub tracks where it shows on your profile that you've had a PR accepted from a given project?  If so, we can make some trivial PR and I'll accept it.  Would that help?

**Pull request closed without merging**
