### PR TITLE
Adoption of existing (new) policy Perl::Critic::Policy::RegularExpressions::RequireDefault

### PR DESCRIPTION
**Pull request by jonasbn**
I created this policy last summer, this PR is an request to get it adopted into Perl::Critic core.

If adopted [the existing GitHub repository](https://github.com/jonasbn/perl-critic-policy-regularexpressions-requiredefault) will be archived and [existing releases on CPAN](https://metacpan.org/release/Perl-Critic-Policy-RegularExpressions-RequireDefault) will be removed.

I hope you find it worth adopting.

jonasbn

### CODE REVIEW

**Comment by petdance** [comment]
Was there discussion of this somewhere that I'm not remembering?  Can you tell us about this?

I'm seeing that it requires Perl 5.14, which is newer than existing Perl::Critic requires.

**Comment by jonasbn** [comment]
Hi @petdance 

No discussion elsewhere you missed out on. I wanted to offer this policy for the Perl::Critic distribution, but trying to get it to play nicely surely had some consequences. The implementation triggers a requirement for Perl 5.14 when enabling the core theme for the policy and getting all the tests to pass. The policy implementation in itself only requires Perl 5.6.0.

An alternative solution could be to disable the policy for the evaluation of Perl::Critic itself instead of enabling the pragma for all policies to avoid violations. The pragma solution or changing all regular-expressions to adhere to the policy, does bump the requirement to 5.14.

How do you propose to proceed?

Looking forward to hearing from you,

jonasbn

**Comment by petdance** [comment]
Mostly I'm wondering if this is a good policy to include.  I'm only slightly aware of the `/a` flag and I don't recall seeing anything recommending that it be something that should be done all the time.

Do you have folks using your module already?  Have you had feedback on it?

**Comment by jonasbn** [comment]
Hi @petdance 

No feedback and I am not aware of any users. My motivation for getting the policy into Perl::Critic is for wider adoption, exposure and collaboration and I actually think that the policy brings something of significance, do note that it only extends the use-case for an existing core Perl feature and it does not offer anything but an integration aiming at improved security for Perl products - at the cost of requiring Perl 5.14 (see previous comment).

Single policies or collections of policies of less prominent CPAN contributors like myself, do not get much attention, so that is my personal motivation/ambition for the policy.

I understand the stance from Perl::Critic - any recommendations for alternative paths would be welcome if a requirement bump to 5.14 is too much of a leap and a decline of the PR is completely acceptable and as always for open source and contributions there are no hard feelings.

**Comment by petdance** [comment]
Thanks. I don't have any strong feelings one way or the other. Let's see if any others have comments.

**Comment by jonasbn** [comment]
I am retracting the PR, I will maintain the policy as a stand-alone policy

**Pull request closed without merging**
