### PR TITLE
[WIP]: Fix everything

### PR DESCRIPTION
**Pull request by oalders**
Try to get green lights for all builds.  Do not merge.

### CODE REVIEW

**Comment by petdance** [comment]
Fix *everything*?  That's quite a boast. :-)

**Comment by petdance** [comment]
I've incorporated some of the changes you're working on into dev.

**Comment by petdance** [comment]
I've cherry-picked some of these commits and pushed to `dev` branch.

**Comment by oalders** [comment]
This branch has been obviated by #868

**Pull request closed without merging**
