### PR TITLE
add Badges

### PR DESCRIPTION
**Pull request by mishin**

### CODE REVIEW

**Comment by dolmen** [comment]
Your clone was outdated when you made your branch.
You can fix that with these commands:
```
git remote add upstream git://github.com/Perl-Critic/Perl-Critic.git
git remote update upstream
git checkout master
git rebase upstream/master
git push -f
```

**Comment by thaljef** [comment]
Thanks @dolmen for figuring that out. I didn't understand what had happened here, so I haven't even figured out what this PR is for.

**Comment by dolmen** [comment]
@thaljef We'll see when it is rebased...

**Comment by thaljef** [comment]
@mishin this is a great addition. But the `README.md` file is generated (periodically) from the POD in `Pinto.pm` using `pod2markdown`. So the markup for the badges should go there. I think you can use a `=for html` or maybe `=for markdown` tag to pass it through. Also, can you apply this on a more recent HEAD, or rebase as @dolmen suggested? Thanks!

**Comment by mishin** [comment]
Well @thaljef Jeffrey, I understand about generated README.md it's common case, I'll think about it.

**Comment by mishin** [comment]
Thanks @dolmen for instructions.

**Comment by mishin** [comment]
Also, I couldn't find Pinto.pm. Where is it?

**Comment by thaljef** [comment]
> Also, I couldn't find Pinto.pm. Where is it?

Oops. I was thinking of another project. That should be `Perl/Critic.pm`.

**Comment by petdance** [comment]
What was this PR supposed to be doing?  What is "add Badges"?

**Comment by thaljef** [comment]
I think this was an attempt to migrate to Dist::Zilla. But it never went
through.

>

**Comment by oalders** [comment]
The relevant commits are https://github.com/Perl-Critic/Perl-Critic/pull/634/commits/68802c1d267ae000dd49d3defb665f47774de078 and https://github.com/Perl-Critic/Perl-Critic/pull/634/commits/f80af033e8dbe0ac0efaf01d5398b2865153f6ca

This PR updates the Travis config and adds some status badges to the README. The Travis part is no longer relevant. Possibly these badges could be added to the `README.md`:

```md
[![Coverage Status](https://coveralls.io/repos/Perl-Critic/Perl-Critic/badge.png?branch=dev)](https://coveralls.io/r/Perl-Critic/Perl-Critic?branch=master)
![Kwalitee status](http://cpants.cpanauthors.org/dist/Perl-Critic.png)
[![GitHub issues](https://img.shields.io/github/issues/Perl-Critic/Perl-Critic.svg)](https://github.com/Perl-Critic/Perl-Critic/issues)
```

**Comment by petdance** [comment]
This is

**Comment by petdance** [comment]
This is so old that I can't do anything with it. We don't use Travis any more, etc.

**Pull request closed without merging**
