### PR TITLE
Allow configuration of other modules which export autodie

### PR DESCRIPTION
**Pull request by autarch**

### CODE REVIEW

**Comment by autarch** [comment]
I'm not sure why 27fb497 is showing up as part of this PR.

Fixes #699

**Comment by autarch** [comment]
It looks like master has commits which are not in the dev branch. Very confusing!

**Comment by petdance** [comment]
> It looks like master has commits which are not in the dev branch. Very confusing!

In the past, dev was done directly on master.  Now we're doing it on dev.

**Comment by autarch** [comment]
I'm pretty sure the test failure on 5.24 is not related to the changes in my branch. I think you may need to configure travis to install more options deps like Test::Pod.

**Comment by autarch** [comment]
ping ...

**Comment by petdance** [comment]
I'll try to look at this today or tomorrow.

**Comment by petdance** [comment]
Done.  Thanks, Dave.

**Comment by autarch** [comment]
I'd love to see this in a release some time soon. It's a very long time thorn in my side.

**Comment by petdance** [comment]
Just uploaded it to PAUSE.  db08d2dd4cca66ff96efee27cd33c9595a655dbd

**Pull request merged**
