### PR TITLE
switch from File::HomeDir to the tiny version

### PR DESCRIPTION
**Pull request by karenetheridge**
..which is a lot leaner and doesn't install a bunch of extra things for
different platforms that are not used

### CODE REVIEW

**Comment by petdance** [comment]
Why stop there?  If all we need is one line of code:

    .($^Oeq Win32&&"$]"<5.016?'$ENV{HOME}||$ENV{USERPROFILE}}':'(<~>)[0]}');

then is there any reason to not just inline that one line of code in the one place it's used Perl::Critic::UserProfile?

**Comment by karenetheridge** [comment]
If you like that better, sure!  I'd add a few spaces though, and quotes around the bareword. :)

The module is not bad for people who look at that code and wonder why all of its bits are necessary and how it works -- because that's all documented in the module.

**Comment by petdance** [comment]
Isn't there a tool somewhere that shows what the trail of dependencies is?  Where I can see what File::HomeDir drags in with it?

**Comment by karenetheridge** [comment]
There used to be one on stratopan, but I think it's gone down, and metacpan doesn't seem to link to it anymore.

**Comment by petdance** [comment]
I made one 12 years ago, so let's see how well it works....

https://metacpan.org/pod/Module::Depends::Tree

**Comment by petdance** [comment]
Turns out that File::HomeDir only brings in File::Which, and the rest are all core modules, so it's not going to be a huge win.  Stlll, I'm glad to do it.

```

**Comment by petdance** [comment]
Turns out that File::HomeDir only brings in File::Which, and the rest are all core modules, so it's not going to be a huge win. Stlll, I'm glad to do it.


```
$ deptree File::HomeDir --mirror ftp://mirror.team-cymru.org/CPAN/
Dependency tree created Sun Dec  9 20:19:04 2018
Created with Module::Depends::Tree 1.00
$ /home/andy/perl5/perlbrew/perls/perl-5.28.0/bin/deptree File::HomeDir

File::HomeDir
    File::Which


Number of times each module is used
    File::HomeDir
    File::Which

2 total modules

File-HomeDir-1.004.tar.gz
    File::HomeDir
File-Which-1.22.tar.gz
    File::Which

2 total packages
```

**Comment by karenetheridge** [comment]
It's the OS-specific dynamic prereqs that always give me grief, as it makes a cpanfile.snapshot file different depending on who runs the update.

Do you want me to adjust the PR to inline the code?

**Comment by petdance** [comment]
> It's the OS-specific dynamic prereqs that always give me grief, as it makes a cpanfile.snapshot file different depending on who runs the update.

I'm not sure what you're saying here.  Are you saying that we should be using the module?

If you have the time to redo the PR to inline it, that would be great, thanks.

**Comment by karenetheridge** [comment]
force-pushed.  Looking closer, I found it should be possible to remove the rest of the logic in `_find_home_dir` as well.

**Comment by petdance** [comment]
```
-    # Check usual environment vars
-    for my $key (qw(HOME USERPROFILE HOMESHARE)) {
-        next if not defined $ENV{$key};
-        return $ENV{$key} if -d $ENV{$key};
-    }
```

Say more about this change, please.  Why is this not necessary?

**Comment by karenetheridge** [comment]
The earlier code is already reading from HOME and USERPROFILE as needed. HOMESHARE looks like a windows thing; USERPROFILE should cover this already. I'm willing to place a wager that the existing code will always return a value, as I trust Father C's investigation in this matter.

**Comment by petdance** [comment]
Thanks. I've incorporated the changes here: 191cf05641e747e55a4d505411cbfe9d6895335c

**Comment by karenetheridge** [comment]
cool, thanks!

**Pull request closed without merging**
