### PR TITLE
Add heredoc test for unreachable code

### PR DESCRIPTION
**Pull request by atoomic**
This is adding some extra coverage for twisted heredoc

### CODE REVIEW

**Comment by petdance** [comment]
Thank you.  What prompted this?  Did something like this come up in your own code?

**Comment by atoomic** [comment]
@petdance I came with this as I had issues while using indented heredoc...
after updating PPI it worked fine :-) I was using an older version without support for it lol
I was going to provide a fix... and first step was to add a unit tests...
I still think it's a good extra test to have in the testsuite

**Comment by petdance** [comment]
Yes, it's a good test.  I just wondered what the backstory was.

**Comment by petdance** [comment]
Merged, thank you.

**Pull request merged**
