### PR TITLE
Fix pod links to satisfy Perl::Critic

### PR DESCRIPTION
**Pull request by oalders**
Satisfy rules around Pod links in order to fix `xt/40_criticize-code.t`.

### CODE REVIEW

**Comment by oalders** [comment]
This could use a careful look.  I may have introduced typos, despite my repeated checks.

**Comment by petdance** [comment]
Thanks for this.  In future, I'd rather leave paragraphs *not* get rewrapped and cause more diffs just because one line in the top of a paragraph got lengthened.

**Comment by oalders** [comment]
> I'd rather leave paragraphs not get rewrapped and cause more diffs just because one line in the top of a paragraph got lengthened.

That's helpful feedback.  Do you want me to revert the wrapping?

**Comment by petdance** [comment]
Also, I seem to recall a recent change that got made somewhere such that we would no longer get complaints about `L<foo>` not being `L<foo|foo>`.  Am I hallucinating?

**Comment by oalders** [comment]
> Also, I seem to recall a recent change that got made somewhere such that we would no longer get complaints about L<foo> not being L<foo|foo>. Am I hallucinating?

I'm seeing 

> By default, links that specify a documentation section (for example, L<Foo/bar>, or L</bar>) are exempt from this Policy.

in https://metacpan.org/pod/Perl::Critic::Policy::Documentation::RequirePodLinksIncludeText

**Comment by petdance** [comment]
Leave the wrapping as-is for now.  Right now I'm more thinking about what we can do to get this PR to not be necessary at all.

**Comment by oalders** [comment]
The lines I changed were failing in the tests.  Is there an issue with the policy?

**Comment by petdance** [comment]
I'm pretty sure that it is no longer necessary with modern POD translators to do `L<Foo||Foo>`.  Maybe the fix we need is to the policy itself.

**Comment by petdance** [comment]
Yes, what I'm saying is that I think that with modern POD translators, the policy is no longer relevant.  I believe that with modern translators, you don't get the problem that this policy is trying to avoid.

**Comment by oalders** [comment]
Oh man, this policy was removed in `578c113b13e1ca2` but it was still installed on my system.

**Comment by oalders** [comment]
```
commit 578c113b13e1ca2318732310b87012cc25b51aeb
Author: Andy Lester <andy@petdance.com>
Date:   Thu Oct 25 23:03:29 2018 -0500

    Remove Documentation::RequirePodLinksIncludeText
```

**Comment by petdance** [comment]
Aha!  I knew I wasn't crazy! :-)

**Pull request closed without merging**
