### PR TITLE
adjust Subroutines::RequireArgUnpacking to PPI 1.277

### PR DESCRIPTION
**Pull request by wchristian**
In https://github.com/Perl-Critic/PPI/pull/289 i merged and released a fix for the detection of labels vs attributes, which broke a test for the policy Subroutines::RequireArgUnpacking and makes it error out when installing Perl::Critic. This PR should fix that.

### CODE REVIEW

**Comment by h3xx** [comment]
May want to bump PPI requirement to new version (or check what version of PPI is running).

**Comment by wchristian** [comment]
Thanks for the reminder, i was too busy thinking about the fix to think of that. :D

**Comment by wchristian** [comment]
Ping? :)

**Comment by wchristian** [comment]
Fwiw, if necessary i'm happy to accept a comaint and release a bugfix for Perl-Critic on this. :)

**Pull request merged**
