### PR TITLE
added code to allow for exempting files based on regex to Modules::RequireExplicitPackage

### PR DESCRIPTION
**Pull request by harleypig**
I'm not sure I've got the right upstream branch, but it's not master! :]

Please let me know about any changes or other problems you have with the way I've done this, suggestions as well.

When you're happy with it, let me know and I'll add documentation to the inline pod and the changes file and whatever else you need changed relative to this and I'll resubmit.

### CODE REVIEW

**Comment by harleypig** [comment]
I changed the check in prepare_to_scan_document method to handle non-existent exempt_files as well as an empty exempt_files.

It occurs to me that it might be desirable to allow for multiple exempt_files fields, but I haven't figured out how to do that and I don't have a lot of time to spend on this.  Is it a simple thing that I'm missing? Is it possible? Is it desired?

**Comment by thaljef** [comment]
Hi Alan. I'm on holiday. Will look at these next week. Thanks for the contributions.

**Comment by harleypig** [comment]
Have fun :]

If it's not a problem I will continue to post questions I have (I've broken some tests) but I won't expect any answers for a week or so.

**Comment by harleypig** [comment]
I realized that I had branched from master instead of dev. I'll branch from dev and test against that.

**Comment by thaljef** [comment]
So I just merged this into master without much thought. But now I'm starting to question this.

What is the motivation for this? Why would you *not* enclose the code in a `package`? And why wouldn't a `## no critic` annotation be sufficient in the cases where you really wanted an exemption?

**Pull request closed without merging**
