### PR TITLE
Use travis-perl-helpers

### PR DESCRIPTION
**Pull request by oalders**
Experiment with travis-perl-helpers.  If this works, it's an easier way to manage the Travis config and it will handle adding coverage reports.

### CODE REVIEW

**Comment by petdance** [comment]
So I'm still not touching this?  I'll wait from an official notification from you.

**Comment by oalders** [comment]
Yeah, I'm not sure if this will work.  I checked the docs and it should handle `Module::Build`, so I'm hopeful.

**Comment by petdance** [comment]
I see you working with Module::Build in here.  My goal is to remove Module::Build soon.

Would it make sense to not mess with the Module::Build options in this PR, and then we'll do the M::B -> EU::MM change in a different PR?

**Comment by oalders** [comment]
I think that's what's going to have to happen.  I wanted to see if we could bypass some of that stuff, but I can see now why that won't work.  I'll pare it down to something simpler and let you know when that's done.  I think I can see how to get this build passing.  Just having an issue with 5.8 timing out on an install of `File::Fetch`.  No idea what that's about.

**Comment by oalders** [comment]
Having said that, you could probably cherry-pick https://github.com/Perl-Critic/Perl-Critic/pull/868/commits/0a6715546b79753eef53b1896b46508c6ae29696

**Comment by petdance** [comment]
Do you see this ready to be merged today?  If not, what do you think about taking a step back and getting P::C running with EU::MM, not Module::Build?  I'd like to get that done because I suspect it will make everything else easier.

**Comment by oalders** [comment]
This is actually ready to merge.  The last remaining build should pass as it's just a typo fix.  When the EU::MM conversion happens this should "just work".

**Comment by oalders** [comment]
Once this is merged you should be able to flip the switch on this at https://coveralls.io/

**Comment by petdance** [comment]
> Once this is merged you should be able to flip the switch on this at https://coveralls.io/

I don't know what you mean by that.

**Comment by oalders** [comment]
If you log in to coveralls.io and enable this repository you'll get notified on pull requests of coverage stats gathered by `Devel::Cover`, so you can see if test coverage is increasing, decreasing or remaining unchanged.

**Comment by petdance** [comment]
OK, I'm looking at coveralls now.  Let me know what I can merge this branch.  I'm going to squash it all down into one commit, and then we can look at moving off of Module::Build.

**Comment by oalders** [comment]
It's already squashed.  One new failure just popped up:

```
#   Failed test 'POD test for blib/lib/Perl/Critic/Policy/Subroutines/ProhibitManyArgs.pm'
#   at /home/travis/perl5/perlbrew/perls/5.28.1/lib/site_perl/5.28.1/Test/Pod.pm line 184.
# blib/lib/Perl/Critic/Policy/Subroutines/ProhibitManyArgs.pm (173): Unterminated C<...> sequence
===(    7028;47   759/2723  10/?  104/?  12/?  92/?   13/195  16... )===# Looks like you failed 1 test of 201.
xt/98_pod_syntax.t ............................ Dubious, test returned 1 (wstat 256, 0x100)
```

That appears to be choking on `Chris Dolan <cdolan@cpan.org>` in `lib/Perl/Critic/Policy/Subroutines/ProhibitManyArgs.pm`.  Not sure how to fix that.

**Comment by petdance** [comment]
> That appears to be choking on Chris Dolan <cdolan@cpan.org> in lib/Perl/Critic/Policy/Subroutines/ProhibitManyArgs.pm. Not sure how to fix that.

No, it was bad POD earlier in the file from me from yesterday.  I've pushed a fix. 575029b

**Comment by oalders** [comment]
I've just rebased and force-pushed.  Hopefully that will be the end of this branch.

**Comment by oalders** [comment]
The Travis build has now passed.  I think the caches got cleared and it exposed an issue with some dependencies which were no longer being installed post-rebase.  Once appveyor comes back green this should be good to merge.  Any further tweaks can wait until after moving away from `Module::Build`.  I guess this will need another squash, but it's easier to do that when merging so we don't have to wait for yet another set of builds.

**Comment by oalders** [comment]
All clear.  This is ready to merge.

**Comment by petdance** [comment]
Merged.  Thank you.

**Comment by oalders** [comment]
Thank you.  Sorry about your inbox. ;)

**Pull request merged**
